### ISSUE TITLE
TZXduino v 1.18, NanoNewBooot diplay OLED XL is not possible

### ISSUE THREAD

**Issue by NuClear235** [rickyelqasem/TZX_Tools#2]
Why is not possible to use 
-TZXduinbio 1.18
-Nano New Boot 
use
OLED XL display? (its menu item is not highlighted)

**Comment by rickyelqasem** [comment]
I left TZXduino in for legacy reasons. When I first made TZX_tools, I had trouble getting TZXduino to work with the 1.3 OLEDs I had. I say legacy because anyone wanting a TZX player would be better off using Maxduino firmware since it offers more features and is compatible with a lot more chips. hope this helps

**Comment by NuClear235** [comment]
Ok, thank You
